######################################################################
# Automatically generated by qmake (3.0) Sun Nov 22 13:25:28 2015
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = a4
INCLUDEPATH += .

# Input
HEADERS += algebra.h polyroots.h raytracing.h
SOURCES += algebra.cpp \
           main.cpp \
           polyroots.cpp \
           raytracing.cpp
